// src/components/demos/vue/Counter.vue
<script setup lang="ts">
import { ref, computed } from 'vue';

const count = ref(0);
const double = computed(() => count.value * 2);
</script>

<template>
  <div class="demo">
    <button type="button" @click="count++">Кликов: {{ count }}</button>
    <span>Удвоенное: {{ double }}</span>
  </div>
</template>

<style scoped>
.demo {
  display: flex;
  gap: var(--space-4);
  align-items: center;
  padding: var(--space-4);
  border: 1px dashed var(--color-border);
  border-radius: var(--radius-md);
}
button {
  padding: var(--space-2) var(--space-4);
  font: inherit;
  cursor: pointer;
}
</style>

// src/components/demos/react/Counter.tsx
import { useState } from 'react';

export default function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div
      style={{
        display: 'flex',
        gap: 'var(--space-4)',
        alignItems: 'center',
        padding: 'var(--space-4)',
        border: '1px dashed var(--color-border)',
        borderRadius: 'var(--radius-md)',
      }}
    >
      <button type="button" onClick={() => setCount((c) => c + 1)} style={{ font: 'inherit', cursor: 'pointer' }}>
        Кликов: {count}
      </button>
      <span>Удвоенное: {count * 2}</span>
    </div>
  );
}
